In [4]:
import numpy as np
from scipy.linalg import lu
from scipy import linalg

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

# This is the first equation LU -> EX1

In [2]:
EX1 = np.array([[2,5],[1,2]])
EX1

array([[2, 5],
       [1, 2]])

In [3]:
p, l, u = lu(EX1)
print("this is p: ", p)
print("this is l: ",l)
print("this is u: ",u)

this is p:  [[1. 0.]
 [0. 1.]]
this is l:  [[1.  0. ]
 [0.5 1. ]]
this is u:  [[ 2.   5. ]
 [ 0.  -0.5]]


In [4]:
p_inv = linalg.inv(p)

In [5]:
y = np.array([[21],[8]])

In [6]:
L_inv = linalg.inv(l)

In [7]:
M = L_inv @ y

In [8]:
U_inv = linalg.inv(u)

In [9]:
x = U_inv @ M
x

array([[-2.],
       [ 5.]])

In [10]:
# y = np.array([[21],[8]])
# EX1 = np.array([[2,5],[1,2]])
def Lu(A, y):
    p, l, u = lu(A)
    y   =(linalg.inv(p))@y
    M = (linalg.inv(l))@y
    x = (linalg.inv(u))@M
    return x

In [11]:
Lu(EX1,y)

array([[-2.],
       [ 5.]])

In [12]:
#Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒
EX2 = np.array([[1,1,1],[4,3,-1],[3,5,3]])
p, l, u = lu(EX2)
y = np.array([[1],[6],[4]])
print("this is p: ", p)
print("this is l: ",l)
print("this is u: ",u)

this is p:  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
this is l:  [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
this is u:  [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]


In [13]:
Lu(EX2,y )

array([[ 1. ],
       [ 0.5],
       [-0.5]])

# This is the first equation LU -> EX2

In [14]:
#Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒
EX2 = np.array([[1,1,1],[4,3,-1],[3,5,3]])


In [15]:
p, l, u = lu(EX2)
y = np.array([[1],[6],[4]])
print("this is p: ", p)
print("this is l: ",l)
print("this is u: ",u)

this is p:  [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
this is l:  [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
this is u:  [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]


In [16]:
U_inv = linalg.inv(u)
P_inv = linalg.inv(p)
L_inv = linalg.inv(l)

In [17]:
y = np.array([[1],[6],[4]])


In [18]:
y_after_edit = P_inv@y

In [19]:
M = L_inv @ y_after_edit
M

array([[ 6.        ],
       [-0.5       ],
       [-0.45454545]])

In [20]:
x = U_inv @ M
x

array([[ 1. ],
       [ 0.5],
       [-0.5]])

### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

In [5]:
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])

y = np.array([[-1],[2],[3]])

# Iterative way for jacobi method

In [22]:
#𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
A = np.array([[5, -2, 3],
     [-3, 9, 1],
     [2, -1, -7]])

y = np.array([[-1],[2],[3]])
x = np.zeros(len(A[0]))
x_new = np.zeros(len(A[0]))
print('k             x1                x2                 x3' )
for i in range(20):
    x_new[0]=(-1+2*x[1]-3*x[2])/5
    x_new[1]=(2+3*x[0]-x[2])/9
    x_new[2]=(3-2*x[0]+x[1])/-7
    x[0]=x_new[0]
    x[1]=x_new[1]
    x[2]=x_new[2]
    print(i+1,    x[0],    x[1],    x[2])
#     print(x)
#     print(x_new)
#     print(np.linalg.norm(x_new-x))
    if  (np.linalg.norm(x_new-x)/ np.linalg.norm(x_new)) < 0.00001:
        break

k             x1                x2                 x3
1 -0.2 0.2222222222222222 -0.42857142857142855


In [23]:
# import numpy as np

# def jacobi(A, b, tolerance):
#     xk_1 = np.zeros_like(b)
#     D = np.diag(A)
#     LplusU = A - np.diag(D)
 
#     #this will be vector 
#     # LplusU @ xk_1 >>> vector 
#     x_k = (b - (LplusU @ xk_1)) / D
    
#     while (np.linalg.norm((x_k - xk_1) , 2) / np.linalg.norm(x_k , 2)) > tolerance:
#         xk_1 = x_k
#         x_k = (b - (LplusU @ xk_1)) / D
    
#     return x_k

In [24]:
jacobi(A, y,0.00001 )

array([[-0.84000076, -0.21889764,  0.10344828],
       [-0.27999609,  0.10551181, -0.37931034],
       [ 0.87999734,  0.39370079, -0.34482759]])

In [25]:
# x1 = 0
# x2 = 0
# x3 = 0

# print("      x1                     x2                     x3")
# for i in range(20):   
#     x1_new=(-1-(-2*x2+3*x3))/5
#     x2_new=(2-(-3*x1 +x3))/9
#     x3_new=(3-(2*x1-x2))/-7
#     x1=x1_new
#     x2=x2_new
#     x3=x3_new
#     print(x1,x2,x3)

In [12]:
# x1 = 0
# x2 = 0
# x3 = 0
# x_new_ = np.array([0,0,0])
# x_ = np.array([0,0,0])
# print("      x1                     x2                     x3")
# for i in range(20):   
#     x1[0]=(-1-(-2*x2+3*x3))/5
#     x2[1]=(2-(-3*x1 +x3))/9
#     x3[3]=(3-(2*x1-x2))/-7
#     x1[0]=x1[0]
#     x2[1]=x2[1]
#     x3[2]=x3[3]
#     print(x1,x2,x3)

# Fanction for Jacobi method

In [13]:
def jacobi(A,y,N=25):
    # Create an initial value                                                                                                                                                             
    x = np.zeros(len(A[0]))
    # Create a vector of the diagonal elements of A and subtract them from A                                                                                                                                                                     
    D = np.diag(A)
    R = A - np.diagflat(D)
    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (y - np.dot(R,x)) / D
    return x

In [14]:
jacobi(A,y,N=25)

array([[-0.84000023, -0.21889764,  0.10344827],
       [-0.27999072,  0.10551181, -0.37931034],
       [ 0.87999425,  0.39370079, -0.34482759]])

In [ ]:
## Jacobi Not Vectorized
epsilon = 0.00001

In [ ]:
## Gauss-Seidel Not Vectorized
epsilon = 0.00001

In [ ]:
## Jacobi Vectorized
epsilon = 0.00001


In [ ]:
## Gauss-Seidel Vectorized
epsilon = 0.00001


[[ 5  0  0]
 [-3  9  0]
 [ 2 -1 -7]]
[[0]
 [0]
 [0]]
[[ 0 -2  3]
 [ 0  0  1]
 [ 0  0  0]]
[[ 0.2         0.          0.        ]
 [ 0.06666667  0.11111111  0.        ]
 [ 0.04761905 -0.01587302 -0.14285714]]
[[-0.2       ]
 [ 0.15555556]
 [-0.50793651]]


# Method for Siedel method 

In [6]:
def gauss_seidel(A, b, tolerance=1e-10, max_iterations=10000):
    
    x = np.zeros_like(b, dtype=np.double)
    
    #Iterate
    for k in range(max_iterations):
        
        x_old  = x.copy()
        
        #Loop over rows
        for i in range(A.shape[0]):
            x[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,(i+1):], x_old[(i+1):])) / A[i ,i]
            
        #Stop condition 
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
            
    return x

In [7]:
gauss_seidel(A, y,1e-10, 10000)

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use np.linalg.solve() to solve the previous system and compare the results.

In [16]:
x = np.linalg.solve(A,y)
x

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [21]:
from scipy.linalg import lu
#scipy.linalg.lu()
P, L, U = lu(A)

In [22]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [-0.6       ,  1.        ,  0.        ],
       [ 0.4       , -0.02564103,  1.        ]])

In [24]:
U

array([[ 5.        , -2.        ,  3.        ],
       [ 0.        ,  7.8       ,  2.8       ],
       [ 0.        ,  0.        , -8.12820513]])